spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/FindAJob
spring.datasource.username=postgres
spring.datasource.password=arthur2006
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.token = 9347rfhfidjrfhf9ejhfndkfjdbhsiuwjbvwiuoeoh
logging.level.org.springframework.security=DEBUG

##Fixed Window Rate Limiter Configuration

#[00:00 - 00:10] → Allow 2 calls
#[00:10 - 00:20] → Allow next 2 calls
#[00:20 - 00:30] → Allow next 2 calls


resilience4j.ratelimiter.instances.loginRateLimiter.limitForPeriod=2
resilience4j.ratelimiter.instances.loginRateLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.loginRateLimiter.timeoutDuration=0s